version: '3.8'

services:
  llm-service:
    build:
      context: .
      dockerfile: Dockerfile.llm
    container_name: kharkov-llm
    ports:
      - "8000:8000"
    environment:
      - CUDA_VISIBLE_DEVICES=0
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    volumes:
      - ~/.cache/huggingface:/root/.cache/huggingface
    restart: unless-stopped
    # healthcheck (temporarily disabled)
    # healthcheck:
    #   test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
    #   interval: 30s
    #   timeout: 10s
    #   retries: 5
    #   start_period: 120s

  web-app:
    build:
      context: .
      dockerfile: Dockerfile.web
    container_name: kharkov-web
    ports:
      - "5000:5000"
    environment:
      - LLM_ENDPOINT=http://llm-service:8000/v1/chat/completions
      - LLM_MODEL=Qwen/Qwen3-VL-8B-Instruct-FP8
      - OPENAI_API_KEY=EMPTY
    volumes:
      - ./uploads:/app/uploads
      - ./results:/app/results
    depends_on:
      - llm-service
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  default:
    name: kharkov-network
